# .github/workflows/gpt-translate.yml
name: GPT Translate

on:
  issue_comment:
    types: [ created ]

jobs:
  gpt_translate:
    if: >
      (contains(github.event.comment.body, '/gpt-translate') ||
      contains(github.event.comment.body, '/gt')) &&
      contains(fromJSON('["OWNER","MEMBER","COLLABORATOR"]'), github.event.comment.author_association)
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - uses: actions/checkout@v4
      - name: Run GPT Translate
        uses: 3ru/gpt-translate@master
        with:
          apikey: ${{ secrets.OPENAI_API_KEY }}
          model: gpt-4o
          prompt: "Please translate the given text into naturalistic {targetLanguage} and output it in {targetFileExt} format. But do not translate the frontmatter section."
